# Generated by Django 4.2.9 on 2024-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
