# Generated by Django 4.2.9 on 2024-04-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_linkedinuser_state'),
        ('events', '0003_alter_events_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
    ]
