# Generated by Django 4.2.9 on 2024-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Advocacy', 'Advocacy'), ('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Humans', 'Humans'), ('Math', 'Math')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
