# Generated by Django 4.2.9 on 2024-04-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_linkedinuser_state'),
        ('jobs', '0002_job_category_job_link_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='postedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
    ]
