# Generated by Django 4.2.9 on 2024-04-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_linkedinuser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('graduationyear', models.IntegerField()),
                ('degreename', models.CharField(max_length=30)),
                ('institutionname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('deadline_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('role', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='linkedinuser',
            name='state',
            field=models.CharField(choices=[('US-MP', 'Northern Mariana Islands'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-TN', 'Tennessee'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-TX', 'Texas'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-UM', 'United States Minor Outlying Islands'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-UT', 'Utah'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-VA', 'Virginia'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-VI', 'Virgin Islands, U.S.'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-PA', 'Pennsylvania'), ('US-VT', 'Vermont'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-WA', 'Washington'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-WI', 'Wisconsin'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-WV', 'West Virginia'), ('US-HI', 'Hawaii')], max_length=5),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
        migrations.AddField(
            model_name='job',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinuser'),
        ),
    ]
